### ISSUE TITLE
proxy相关

### ISSUE THREAD

**Issue by LuckyFork** [jun-wei-zeng/douban_movie_spider_mrs#2]
请问大佬proxy当时购买的是什么量级的？感谢大佬的解答

**Comment by junweizeng** [comment]
你好，我当时购买的proxy是包量套餐（1000条），如果数据量需求比较大的话可以接着续。

**Comment by LuckyFork** [comment]
好的谢谢！非常感谢您的回复！
---- 回复的原邮件 ----
| 发件人 | Junwei ***@***.***> |
| 发送日期 | 2024年05月12日 15:16 |
| 收件人 | junweizeng/douban_movie_spider_mrs ***@***.***> |
| 抄送人 | LuckyFork ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [junweizeng/douban_movie_spider_mrs] proxy相关 (Issue #2) |

你好，我当时购买的proxy是包量套餐（1000条），如果数据量需求比较大的话可以接着续。

**Comment by junweizeng** [comment]
你如果有其他问题可以重新开一个新的issue，我这里关闭该issue表示完成。

**Comment by LuckyFork** [comment]
好的，明白


---- 回复的原邮件 ----
| 发件人 | Junwei ***@***.***> |
| 发送日期 | 2024年05月12日 15:27 |
| 收件人 | junweizeng/douban_movie_spider_mrs ***@***.***> |
| 抄送人 | LuckyFork ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [junweizeng/douban_movie_spider_mrs] proxy相关 (Issue #2) |

你如果有其他问题可以重新开一个新的issue，我这里关闭该issue表示完成。
