### ISSUE TITLE
你好，为什么使用代理一直报错，是什么原因

### ISSUE THREAD

**Issue by jun-alt** [jun-wei-zeng/douban_movie_spider_mrs#3]
设置的proxy为：111.225.152.238:8089
Error (MaxRetryError("HTTPSConnectionPool(host='movie.douban.com', port=443): Max retries exceeded with url: /j/new_search_subjects?sort=U&range=0,10&tags=%E7%94%B5%E5%BD%B1&start=0 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027CDBA18E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"),)

**Comment by junweizeng** [comment]
![image](https://github.com/user-attachments/assets/fd2cfdce-1cb7-4664-989e-10e2ba3b1b43)

我测了一下，你这个代理ip好像有问题，你可以把使用代理的代码注释掉，看下还有没有这个问题。

**Comment by jun-alt** [comment]
换了代理ip已经好了，谢谢
